### ISSUE TITLE
Error: Cannot find module 'apollo-server-errors'

### ISSUE THREAD

**Issue by wkylin** [mandiwise/basic-apollo-federation-demo#18]
[dev:gateway] Error: Cannot find module 'apollo-server-errors'
[dev:gateway] Require stack:
[dev:gateway] - D:\workdoc\workspace\basic-apollo-federation-demo\node_modules\@apollo\gateway\dist\datasources\RemoteGraphQLDataSource.js
[dev:gateway] - D:\workdoc\workspace\basic-apollo-federation-demo\node_modules\@apollo\gateway\dist\index.js
[dev:gateway] - D:\workdoc\workspace\basic-apollo-federation-demo\index.js
[dev:gateway]     at Object.<anonymous> (D:\workdoc\workspace\basic-apollo-federation-demo\node_modules\@apollo\gateway\dist\datasources\RemoteGraphQLDataSource.js:26:32)       
[dev:gateway]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10) {
[dev:gateway]   code: 'MODULE_NOT_FOUND',
[dev:gateway]   requireStack: [
[dev:gateway]     'D:\\workdoc\\workspace\\basic-apollo-federation-demo\\node_modules\\@apollo\\gateway\\dist\\datasources\\RemoteGraphQLDataSource.js',
[dev:gateway]     'D:\\workdoc\\workspace\\basic-apollo-federation-demo\\node_modules\\@apollo\\gateway\\dist\\index.js',
[dev:gateway]     'D:\\workdoc\\workspace\\basic-apollo-federation-demo\\index.js'
[dev:gateway]   ]
[dev:gateway] }

**Comment by bakshiabhisek** [comment]
Has anyone found an solution for this ?
